server:
  port: 8888
spring:
  application:
     name: eureka-config
#  profiles:
#      active: dev
  cloud:
      config:
        server:
          git:
            uri: https://github.com/xyy945/springCloud-demo.git #配置git仓库地址
            searchPaths: config #配置仓库路径,是.git的相对路径下，同一文件夹下
            username: xyy945 #访问git仓库的用户名
            password: cwj_echo_945 #访问git仓库的用户密码
        label: master #配置仓库的分支
#设置服务注册中心地址，指向另一个注册中心
eureka:
  instance:
      hostname: ${spring.cloud.client.ipAddress}
      instanceId: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

