eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8991
spring:
  application:
     name: eureka-provider
#关闭配置中心安全认证
management:
  security:
     enabled: false
